name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Installation
        run: npm install
      - name: Check immutable package-lock.json
        run: git diff --exit-code